In [1]:
# PANDAS 패키지 불러오기
import pandas as pd

# CSV 파일을 읽어 Data Frame 변수에 저장하기
customerData = pd.read_csv("../dataset/customerdata.csv")

# 컬럼헤더 재정의
customerData.columns = ['CUSTID','AVGPRICE','EMI','DEVICECOUNT','PRODUCTAGE','CUSTTYPE']

# 데이터 VIEW

# CSV 파일로 저장
customerData.to_csv("../dataset/customerdata_out.csv", index=False)
customerData.head()

   CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.900000    3          6.4    1.679181  Big-Screen-lover
1  A14219  3642.441950    2          4.0    2.682023      Sleeping-dog
2  A15312  3653.884565    2          5.0    3.208202      Sleeping-dog
3  A16605  3713.211107    2          6.6    0.900000        Early-bird
4  B10634  3391.074215    2          4.2    2.453656      Sleeping-dog

In [2]:
import pandas as pd
from sqlalchemy import create_engine

#  DB 커넥션 열기
engine = create_engine('oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl')

#  DB 테이블을 읽어 Data Frame 변수에 저장하기
customerData = pd.read_sql_query('SELECT * FROM customerdata', engine)

#  컬럼헤더 재정의
customerData.columns = ['CUSTID','AVGPRICE','EMI','DEVICECOUNT','PRODUCTAGE','CUSTTYPE']

#  데이터 VIEW
print(customerData.head)

#  데이터 저장
resultname = 'oracleresult'
customerData.to_sql(resultname, engine, if_exists='replace', index=False)

<bound method NDFrame.head of      CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3          6.4    1.679181  Big-Screen-lover
1    A14219  3642.441950    2          4.0    2.682023      Sleeping-dog
2    A15312  3653.884565    2          5.0    3.208202      Sleeping-dog
3    A16605  3713.211107    2          6.6    0.900000        Early-bird
4    B10634  3391.074215    2          4.2    2.453656      Sleeping-dog
5    B16849  3755.263391    2          4.7    2.786665      Sleeping-dog
6    B18816  3213.911446    2          6.4    0.900000        Early-bird
7    C10639  3516.500000    2          5.2    2.564830  Big-Screen-lover
8    C12717  3732.900000    2          5.7    2.069995  Big-Screen-lover
9    C15050  4020.173425    2          4.9    3.013440      Sleeping-dog
10   C18306  4005.005142    2          4.7    3.113618      Sleeping-dog
11   C18622  3246.000000    1          5.0    1.891624  Big-Screen-lover
12   C19178  3624.700000    2          5.6    2.137246  Big-Screen-lover
13   D11795  2991.014703    2          6.4    0.800000        Early-bird
14   D13030  3227.855655    2          4.8    3.467370      Sleeping-dog
15   D15289  4165.700000    2          6.9    2.911016  Big-Screen-lover
16   D17241  4166.533130    2          4.7    2.577757      Sleeping-dog
17   D17880  3383.145853    2          4.5    2.903990      Sleeping-dog
18   E10778  4165.700000    2          6.7    2.122257  Big-Screen-lover
19   E11917  3516.500000    2          5.5    2.087540  Big-Screen-lover
20   E16075  3418.048887    2          4.2    2.771469      Sleeping-dog
21   E16221  3408.300000    2          5.0    1.988682  Big-Screen-lover
22   E18145  3408.300000    2          4.9    1.521029  Big-Screen-lover
23   E19404  3764.940414    2          6.5    0.900000        Early-bird
24   F10222  3191.065822    2          6.5    0.900000        Early-bird
25   F12979  4165.700000    2          6.1    2.128362  Big-Screen-lover
26   F14866  3137.800000    2          5.1    1.725892  Big-Screen-lover
27   F17131  3179.708359    3          6.5    1.100000        Early-bird
28   F18646  3334.244233    2          4.5    3.273196      Sleeping-dog
29   F19938  3732.900000    2          5.4    2.011303  Big-Screen-lover
..      ...          ...  ...          ...         ...               ...
120  U16894  3234.465609    2          3.6    2.606419      Sleeping-dog
121  U17547  3313.905655    2          4.0    2.448368      Sleeping-dog
122  U17748  3394.152840    2          4.0    2.185742      Sleeping-dog
123  V10654  3902.329790    2          4.6    3.260149      Sleeping-dog
124  V16516  3149.259875    2          4.1    2.410823      Sleeping-dog
125  V16704  2605.631083    2          6.6    0.900000        Early-bird
126  V18566  3527.701867    3          6.5    0.900000        Early-bird
127  V19072  3462.400000    2          5.3    1.922932  Big-Screen-lover
128  W10832  3527.360507    2          4.1    2.136971      Sleeping-dog
129  W13032  4003.400000    2          6.1    2.519623  Big-Screen-lover
130  W13404  4296.873743    3          6.5    1.100000        Early-bird
131  W13995  2411.008838    2          6.4    1.000000        Early-bird
132  W16193  3402.729703    2          6.4    0.900000        Early-bird
133  W18228  3480.455474    2          6.4    0.900000        Early-bird
134  X10158  3949.300000    2          6.3    1.815666  Big-Screen-lover
135  X13390  2947.543982    3          6.3    1.100000        Early-bird
136  X14259  3481.314549    2          4.3    2.528063      Sleeping-dog
137  X19598  3516.500000    2          5.1    2.646259  Big-Screen-lover
138  X19768  3486.085831    2          4.6    2.835355      Sleeping-dog
139  Y10906  3408.300000    2          6.0    2.131432  Big-Screen-lover
140  Y12458  2976.211190    1          3.5    2.199677      Sleeping-dog
141  Y13678  3408.300000    2          5.6    2.084005  Big-Screen-lover
142  Z11525  3259.018704    3          6.4    0.900000        Early-bird
143  Z12343  3498.896985    2          6.6    0.900000        Early-bird
144  Z12772  3029.600000    2          4.9    2.093035  Big-Screen-lover
145  Z13253  3678.800000    2          5.9    2.463670  Big-Screen-lover
146  Z13534  3662.437527    3          6.6    0.900000        Early-bird
147  Z16428  3516.500000    2          5.8    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2          5.6    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2          6.7    1.200000        Early-bird

[150 rows x 6 columns]>

### Mysql connection

In [5]:
#  PANDAS 패키지 불러오기
import pandas as pd
import pymysql
from sqlalchemy import create_engine

# DB 커넥션 열기
engine_oracle = create_engine('oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl')
engine_mysql = create_engine('mysql+pymysql://root:P@ssw0rd@192.168.110.112:3306/kopo')

# DB 테이블을 읽어 Data Frame 변수에 저장하기
customerData = pd.read_sql_query('SELECT * FROM customerdata', engine_oracle) 

# 컬럼헤더 재정의
customerData.columns = ['CUSTID','AVGPRICE','EMI','DEVICECOUNT','PRODUCTAGE','CUSTTYPE']

#  데이터 VIEW
print(customerData.head())

#  데이터 저장
resultname = 'customerdata'
customerData.to_sql(resultname,engine_mysql,if_exists='replace',index=False)

   CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  T11473  4165.700000    3          6.7    1.780674  Big-Screen-lover
1  T11512  3428.518977    2          4.7    3.483573      Sleeping-dog
2  T12735  3993.263836    2          4.8    2.535829      Sleeping-dog
3  T13866  3732.900000    2          5.1    2.812051  Big-Screen-lover
4  T16556  3166.013276    2          6.4    0.900000        Early-bird